services:
  - type: web
    name: tg-media-bot
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: SECRET_TOKEN
        sync: false
      - key: MAX_FILE_MB
        value: "18"
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1