services:
  - type: web
    name: massive-helper
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: BOT_TOKEN
        value: ""
      - key: WEBHOOK_URL
        value: ""
      - key: MAX_FILE_MB
        value: "18"
